#pragma once

#include <nlohmann/json.hpp>
using json = nlohmann::json;

#define STYLE_TYPES_COUNT 32

struct NotifyInteractions
{
	const char *label;
	const char *id;
};

#ifdef __WINDOWS__
std::string osSlash = "\\";
#else
std::string osSlash = "/";
#endif

wxString project_path = wxString("");
wxString icons_dir = wxString("");
wxString current_openned_path = wxString("");
wxString osName;

std::string menuDirPath;
std::string menuFilePath;

std::string appExecutablePath;
std::string applicationPath;

std::string project_name;
std::string assetsDir;

std::string config_path;

json UserTheme;
json UserConfigs;

wxFrame *mainFrame = nullptr;

enum
{
	ID_MAIN_FRAME = -1,
	ID_PROJECT_TOGGLER,
	ID_Quit,
	ID_EXIT_SEARCH_CONTAINER,
	ID_SAVE_ALL,
	ID_NEW_WINDOW,
	ID_ABOUT,
	ID_NEW_FILE,
	ID_OPEN_FOLDER,
	ID_EDIT_SETTINGS,
	ID_OPEN_FILE,
	ID_TABS,
	ID_SIDE_NAVIGATION,
	ID_SAVE_AS,
	ID_CLOSE_FILE,
	ID_TOGGLE_COMMENT_BLOCK,
	ID_CODE_CONTAINER,
	ID_TOGGLE_MENU_BAR_VIEW,
	ID_TOGGLE_COMMENT_LINE,
	ID_GOTO_SEARCHPAGE,
	ID_SELECT_ALL,
	ID_SEARCH_CONTAINER,
	ID_SELECT_LINE,
	ID_TOGGLE_FILE_TREE_VIEW,
	ID_HIDDE_SIDE_NAV,
	ID_TOGGLE_STATUS_BAR_VIEW,
	ID_NAVIGATION_BUTTONS,
	ID_CLOSE_FOLDER,
	ID_TOGGLE_FIND,
	ID_SEARCH_FILES,
	ID_SEARCH_FILES_PANEL,
	ID_FILES_TREE_TOP_CONTENT,
	ID_TOGGLE_TAB_BAR_VIEW,
	ID_RENAME_FILE,
	ID_TOGGLE_MINI_MAP_VIEW,
	ID_RENAME_DIR,
	ID_CODE_MAP,
	ID_CODE_EDITOR,
	ID_CODE_BLOCK,
	ID_OPEN_TERMINAL,
	ID_APPLICATION_CONTENT,
	ID_CENTERED_CONTENT,
	ID_EMPYT_WINDOW,
	ID_CREATE_DIR,
	ID_CREATE_FILE,
	ID_MAIN_CONTAINER_SPLITTER,
	ID_MAIN_SPLITTER,
	ID_EXIT,
	ID_TABS_RIGHT_MENU,
	ID_SERVICAL_CONTAINER,
	ID_DELETE_DIR,
	ID_TOGGLE_COMMENT,
	ID_DELETE_FILE,
	ID_GLOBAL_NAVIGATION,
	ID_EXIT_TERMINAL,
	ID_TABS_CONTAINER,
	ID_TOGGLE_CONTROL_PANEL,
	ID_CODE_ARROWS_PRESS,
	ID_TERMINAL,
	ID_CONTROL_PANEL,
	ID_EXIT_CONTROL_PANEL,
	ID_MAIN_CONTAINER,
	ID_FILES_TREE,
	ID_CONTROL_PANEL_UP,
	ID_CONTROL_PANEL_DOWN,
	ID_CONTROL_PANEL_SELECT,
	ID_MAIN_CODE,
	ID_STATUS_BAR,
	ID_OPEN_FOLDER_BUTTON,
	ID_MENU_BAR,
	ID_FILES_TREE_TOP_MENU,
	ID_PROJECT_FILES,
	ID_PROJECT_TOOLS_BAR,
	ID_PROJECT_FILES_CTN,
	ID_FILES_TREE_EMPTY,
	ID_NOTIFY_PANEL,
	ID_PJT_TOOLS_PJTNAME,
	ID_PJT_TOOLS_ARROW,
	ID_FILE_DOCKER,
	ID_SEARCH_PAGE_INPUT,
	ID_TRIPLE_A,
	ID_BUILDER_PAGE,
	ID_EXTENSIONS_PAGE,
	ID_SETTINGS_PAGE,
	ID_FOCUS_PAGE,
	ID_STTSBAR_FILE_EXT,
	ID_STTSBAR_TAB_SIZE,
	ID_STTSBAR_CODELOCALE,
	ID_FOCUS_MODE,
	ID_CLOSE_ALL_FILES,
	ID_SIDE_CONTAINER,
	BORDER_SIDE_TOP,
	BORDER_SIDE_BOTTOM,
	BORDER_SIDE_LEFT,
	BORDER_SIDE_RIGHT,
};